# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qdrant_openapi_client
from qdrant_openapi_client.model.alias_operations_any_of1_delete_alias import AliasOperationsAnyOf1DeleteAlias
globals()['AliasOperationsAnyOf1DeleteAlias'] = AliasOperationsAnyOf1DeleteAlias
from qdrant_openapi_client.model.alias_operations_any_of1 import AliasOperationsAnyOf1


class TestAliasOperationsAnyOf1(unittest.TestCase):
    """AliasOperationsAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAliasOperationsAnyOf1(self):
        """Test AliasOperationsAnyOf1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AliasOperationsAnyOf1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
