# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.point_insert_ops_any_of import PointInsertOpsAnyOf
from openapi_client.model.point_insert_ops_any_of1 import PointInsertOpsAnyOf1
from openapi_client.model.point_insert_ops_any_of_batch import PointInsertOpsAnyOfBatch
from openapi_client.model.point_struct import PointStruct
globals()['PointInsertOpsAnyOf'] = PointInsertOpsAnyOf
globals()['PointInsertOpsAnyOf1'] = PointInsertOpsAnyOf1
globals()['PointInsertOpsAnyOfBatch'] = PointInsertOpsAnyOfBatch
globals()['PointStruct'] = PointStruct
from openapi_client.model.point_insert_ops import PointInsertOps


class TestPointInsertOps(unittest.TestCase):
    """PointInsertOps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointInsertOps(self):
        """Test PointInsertOps"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointInsertOps()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
