# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qdrant_openapi_client
from qdrant_openapi_client.model.alias_operations_any_of import AliasOperationsAnyOf
from qdrant_openapi_client.model.alias_operations_any_of1 import AliasOperationsAnyOf1
from qdrant_openapi_client.model.alias_operations_any_of1_delete_alias import AliasOperationsAnyOf1DeleteAlias
from qdrant_openapi_client.model.alias_operations_any_of2 import AliasOperationsAnyOf2
from qdrant_openapi_client.model.alias_operations_any_of2_rename_alias import AliasOperationsAnyOf2RenameAlias
from qdrant_openapi_client.model.alias_operations_any_of_create_alias import AliasOperationsAnyOfCreateAlias
globals()['AliasOperationsAnyOf'] = AliasOperationsAnyOf
globals()['AliasOperationsAnyOf1'] = AliasOperationsAnyOf1
globals()['AliasOperationsAnyOf1DeleteAlias'] = AliasOperationsAnyOf1DeleteAlias
globals()['AliasOperationsAnyOf2'] = AliasOperationsAnyOf2
globals()['AliasOperationsAnyOf2RenameAlias'] = AliasOperationsAnyOf2RenameAlias
globals()['AliasOperationsAnyOfCreateAlias'] = AliasOperationsAnyOfCreateAlias
from qdrant_openapi_client.model.alias_operations import AliasOperations


class TestAliasOperations(unittest.TestCase):
    """AliasOperations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAliasOperations(self):
        """Test AliasOperations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AliasOperations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
