# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qdrant_openapi_client
from qdrant_openapi_client.model.point_struct import PointStruct
globals()['PointStruct'] = PointStruct
from qdrant_openapi_client.model.point_insert_ops_any_of1 import PointInsertOpsAnyOf1


class TestPointInsertOpsAnyOf1(unittest.TestCase):
    """PointInsertOpsAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointInsertOpsAnyOf1(self):
        """Test PointInsertOpsAnyOf1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointInsertOpsAnyOf1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
