# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.geo_bounding_box import GeoBoundingBox


class TestGeoBoundingBox(unittest.TestCase):
    """GeoBoundingBox unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoBoundingBox(self):
        """Test GeoBoundingBox"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GeoBoundingBox()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
