# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.point_insert_ops_any_of_batch import PointInsertOpsAnyOfBatch
globals()['PointInsertOpsAnyOfBatch'] = PointInsertOpsAnyOfBatch
from openapi_client.model.point_insert_ops_any_of import PointInsertOpsAnyOf


class TestPointInsertOpsAnyOf(unittest.TestCase):
    """PointInsertOpsAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointInsertOpsAnyOf(self):
        """Test PointInsertOpsAnyOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointInsertOpsAnyOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
