# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payload_variant_for_geo_point import PayloadVariantForGeoPoint
globals()['PayloadVariantForGeoPoint'] = PayloadVariantForGeoPoint
from openapi_client.model.payload_interface_any_of3 import PayloadInterfaceAnyOf3


class TestPayloadInterfaceAnyOf3(unittest.TestCase):
    """PayloadInterfaceAnyOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadInterfaceAnyOf3(self):
        """Test PayloadInterfaceAnyOf3"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayloadInterfaceAnyOf3()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
