# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""

import unittest

from qdrant_openapi_client.model.condition import Condition
from qdrant_openapi_client.model.filter import Filter
from qdrant_openapi_client.model.range import Range
from qdrant_openapi_client.model.search_request import SearchRequest


class TestSearchRequest(unittest.TestCase):
    """SearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSearchRequest(self):
        """Test SearchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        model = SearchRequest(
            top=10,
            vector=[1.0, 2.0, 3.0],
            filter=Filter(
                must=[
                    Condition(range=Range(
                        key="my_field",
                        gt=42.2
                    ))
                ]
            )
        )  # noqa: E501

        print(model.to_dict())


if __name__ == '__main__':
    unittest.main()
