# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.alias_operations_any_of2_rename_alias import AliasOperationsAnyOf2RenameAlias


class TestAliasOperationsAnyOf2RenameAlias(unittest.TestCase):
    """AliasOperationsAnyOf2RenameAlias unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAliasOperationsAnyOf2RenameAlias(self):
        """Test AliasOperationsAnyOf2RenameAlias"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AliasOperationsAnyOf2RenameAlias()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
