# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qdrant_openapi_client
from qdrant_openapi_client.model.payload_interface import PayloadInterface
globals()['PayloadInterface'] = PayloadInterface
from qdrant_openapi_client.model.point_struct import PointStruct


class TestPointStruct(unittest.TestCase):
    """PointStruct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPointStruct(self):
        """Test PointStruct"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PointStruct()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
