# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import qdrant_openapi_client
from qdrant_openapi_client.model.payload_variant_for_int64 import PayloadVariantForInt64
globals()['PayloadVariantForInt64'] = PayloadVariantForInt64
from qdrant_openapi_client.model.payload_interface_any_of1 import PayloadInterfaceAnyOf1


class TestPayloadInterfaceAnyOf1(unittest.TestCase):
    """PayloadInterfaceAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadInterfaceAnyOf1(self):
        """Test PayloadInterfaceAnyOf1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PayloadInterfaceAnyOf1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
