# coding: utf-8

"""
    Qdrant API

    API description for Qdrant vector search engine. Describes CRUD and search operations on collections of points (vectors with payload).  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: andrey@vasnetsov.com
    Generated by: https://openapi-generator.tech
"""

import unittest

from openapi_client.model.geo_point import GeoPoint
from openapi_client.model.payload_type_any_of import PayloadTypeAnyOf
from openapi_client.model.payload_type_any_of1 import PayloadTypeAnyOf1
from openapi_client.model.payload_type_any_of2 import PayloadTypeAnyOf2
from openapi_client.model.payload_type_any_of3 import PayloadTypeAnyOf3

globals()['GeoPoint'] = GeoPoint
globals()['PayloadTypeAnyOf'] = PayloadTypeAnyOf
globals()['PayloadTypeAnyOf1'] = PayloadTypeAnyOf1
globals()['PayloadTypeAnyOf2'] = PayloadTypeAnyOf2
globals()['PayloadTypeAnyOf3'] = PayloadTypeAnyOf3
from openapi_client.model.payload_type import PayloadType


class TestPayloadType(unittest.TestCase):
    """PayloadType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPayloadType(self):
        """Test PayloadType"""
        # FIXME: construct object with mandatory attributes with example values
        model = PayloadType(value=[1, 2, 3], type='integer')  # noqa: E501


if __name__ == '__main__':
    unittest.main()
